# Role Bindings are used to attach roles to single users or groups of users
roleBindings:
  - metadata:
      # Metadata properties will be shown in the UI. You can omit it if you want to
      name: Developers
    subjects:
      # You can specify all groups or users from different providers here which shall be bound to the same role
      - kind: group
        provider: Google
        name: dev-team-cloudhut@yourcompany.com
      - kind: user
        provider: Google
        name: john.doe@yourcompany.com
      - kind: group
        provider: GitHub
        organization: cloudhut
        name: kafka-owl-devs # This resolves to the team within the org
      - kind: user
        provider: GitHub
        name: rikimaru0345
      - kind: group
        provider: Okta
        name: 00qri1afoAa12G9js04x6 # Okta Group ID
      - kind: user
        provider: Okta
        name: weeco91@gmail.com # Okta user login
    roleName: developer
