roles:
  # developer role can:
  # - administrate all consumer groups
  # - all view permissions on all topics except battle-logs
  # - 3 atomic permissions are allowed on the battle-logs topic
  - name: developer
    permissions:
      - resource: consumerGroups
        includes: ["/.*/"]
        allowedActions: ["admin"]

      - resource: topics
        includes: ["/.*/"]
        excludes: ["battle-logs"]
        allowedActions: ["viewer"]

      # ACLs do not have includes or excludes as there are no permissions implemented for individual ACL rules
      - resource: acls
        allowedActions: ["viewAcl"]

      - resource: topics
        includes: ["battle-logs"]
        # Other actions are "viewMessages", "useSearchFilter", "viewConsumers"
        allowedActions: ["seeTopic", "viewPartitions", "viewConfig"]
