###################################################################
# Commented config settings are optional and show the defaults
###################################################################
kafka:
  brokers:
    - broker-0.mycompany.com:19092
    - broker-1.mycompany.com:19092
    - broker-2.mycompany.com:19092
  # clientId: kowl
  # sasl:
  #   enabled: false
  #   useHandshake: true
  #   username:
  #   password: # This can be set via the --kafka.sasl.password flag as well
  #   mechanism: PLAIN # PLAIN, SCRAM-SHA-256, SCRAM-SHA-512 and GSSAPI are supported
  #   gssapi:
  #     authType:
  #     keyTabPath:
  #     kerberosConfigPath:
  #     serviceName:
  #     username:
  #     password: # can be set via the --kafka.sasl.gssapi.password flag as well
  #     realm:
  # tls:
  #   enabled: false
  #   caFilepath:
  #   certFilepath:
  #   keyFilepath:
  #   passphrase: # This can be set via the --kafka.tls.passphrase flag as well
  #   insecureSkipTlsVerify: false
  # schemaRegistry:
  #   enabled: true
  #   urls: [] # Url with scheme is required, e.g. ["http://localhost:8081"]
  #   username: # Basic auth username
  #   password: # Basic auth password
  #   bearerToken:

# Git config to use for embedded topic documentation, see /docs/features/topic-documentation.md for more details
# git:
#   topicDocumentation:
#     enabled: false
#     repoUrl:
#     branch:
#     refreshInterval: 1m
#   basicAuth:
#     enabled: false
#     username:
#     password: #  This can be set via the via the --git.basic-auth.password flag as well
#   ssh:
#     enabled: false
#     username:
#     privateKey: # This can be set via the via the --git.ssh.private-key flag as well
#     privateKeyFilepath:
#     passphrase: # This can be set via the via the --git.ssh.passphrase flag as well

# server:
#   listenPort: 8080
#   gracefulShutdownTimeout: 30s
#   listenPort: 8080
#   readTimeout: 30s
#   writeTimeout: 30s
#   idleTimeout: 30s
#   compressionLevel: 4
#   basePath: # Sub-path under which kowl is hosted. See 'docs/features/hosting.md' for more information
#   setBasePathFromXForwardedPrefix: true # Whether or not to check the 'X-Forwarded-Prefix' header to (potentially) override 'basePath'
#   stripPrefix: true # Whether or not kowl should strip the prefix internally

# logger:
#   level: info

# Only relevant for developers, who might want to run the frontend separately
# serveFrontend: true

# Prefix for all exported prometheus metrics
# metricsNamespace: kowl
