name: Build & Push Docker Image

on:
  push:
    tags:
      - '*'
    branches:
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
        with:
          driver-opts: image=moby/buildkit:v0.10.3,network=host

      - name: Set Release Date
        run: |
          echo "BUILT_AT=$(date +%s)" >> ${GITHUB_ENV}

      - name: Docker meta
        id: docker_meta
        uses: docker/metadata-action@v4
        with:
          images: |
            vectorized/console
          tags: |
            type=sha,prefix={{branch}}-,format=short,enable={{is_default_branch}}
            type=semver,pattern={{raw}},enable=${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.docker_meta.outputs.tags }}
          build-args: |
            VERSION=${{ fromJSON(steps.docker_meta.outputs.json).labels['org.opencontainers.image.version'] }}
            BUILD_TIMESTAMP=${{ env.BUILT_AT }}
            GIT_SHA=${{ github.sha }}
            GIT_REF=master
            BUILT_FROM_PUSH=${{ !startsWith(github.ref, 'refs/tags/v') }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
