
name: Create Docker Image on Release

on:
  release:
    types: [published] # we could also use: created, or prereleased

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Login to GitHub Package Registry
        env:
          GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}
        run: docker login docker.pkg.github.com -u rikimaru0345 -p ${GITHUB_PACKAGE_REGISTRY_TOKEN}

      - name: Build Docker Image
        run:
          docker build
          --build-arg "COMMIT_SHA=${GITHUB_SHA}"
          --build-arg "GITHUB_REF=${GITHUB_REF}"
          -t docker.pkg.github.com/kafka-owl/kafka-owl/kafka-owl:latest
          -t docker.pkg.github.com/kafka-owl/kafka-owl/kafka-owl:${GITHUB_SHA}
          -t docker.pkg.github.com/kafka-owl/kafka-owl/kafka-owl:${GITHUB_REF}
          .

      - name: Push Image
        run: |
          docker push docker.pkg.github.com/kafka-owl/kafka-owl/kafka-owl:latest
          docker push docker.pkg.github.com/kafka-owl/kafka-owl/kafka-owl:${GITHUB_SHA}
          docker push docker.pkg.github.com/kafka-owl/kafka-owl/kafka-owl:${GITHUB_REF}
