name: Lint and Test Charts

on:
  push:
    branches:
      - master
    paths:
      - "helm/**"
      - ".github/workflows/helm-test.yml"
  pull_request:
    branches:
      - master
    paths:
      - "helm/**"
      - ".github/workflows/helm-test.yml"

jobs:
  helm-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up latest stable Helm version
        uses: azure/setup-helm@v3

      # Python is required because ct lint runs Yamale and yamllint which requires Python
      - uses: actions/setup-python@v4
        with:
          python-version: '3.7'

      - name: Set up chart-testing
        uses: helm/chart-testing-action@v2.2.1

      - name: Run chart-testing (lint)
        run: ct lint --debug --chart-dirs helm --target-branch ${{ github.event.repository.default_branch }}
