
name: Docker Image for master branch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Extract ref/branch name
        shell: bash
        run: echo "##[set-output name=ref;]$(echo ${GITHUB_REF##*/})"
        id: extract_ref

      - name: Set timestamp
        shell: bash
        run: echo "::set-output name=time::$(echo date +%s)"
        id: set_timestamp

      - name: Login to Quay
        env:
          QUAY_ENCRYPTED_PASS: ${{ secrets.QUAY_ENCRYPTED_PASS }}
        run: docker login quay.io -u=cloudhut+github_push -p=${QUAY_ENCRYPTED_PASS}

      - name: Build Docker Image
        run:
          docker build
          --build-arg "GIT_SHA=${GITHUB_SHA}"
          --build-arg "GIT_REF=${{ steps.extract_ref.outputs.ref }}"
          --build-arg "TIMESTAMP=${{ steps.set_timestamp.outputs.time }}"
          -t quay.io/cloudhut/kafka-owl:master
          .

      - name: Push Image
        run: |
          docker push quay.io/cloudhut/kafka-owl:master
