
name: Docker Image for master branch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Extract ref/branch name
        shell: bash
        run: echo "##[set-output name=ref;]$(echo ${GITHUB_REF##*/})"
        id: extract_ref

      # - name: Login to GitHub Package Registry
      #   env:
      #     GITHUB_PACKAGE_REGISTRY_TOKEN: ${{ secrets.GITHUB_PACKAGE_REGISTRY_TOKEN }}
      #   run: docker login docker.pkg.github.com -u rikimaru0345 -p ${GITHUB_PACKAGE_REGISTRY_TOKEN}

      - name: Build Docker Image
        run:
          docker build
          --build-arg "COMMIT_SHA=${GITHUB_SHA}"
          --build-arg "GITHUB_REF=${{ steps.extract_ref.outputs.ref }}"
          -t docker.pkg.github.com/kafka-owl/kafka-owl/kafka-owl:master
          .

      # - name: Push Image
      #   run: |
      #     docker push docker.pkg.github.com/kafka-owl/kafka-owl/kafka-owl:master
