
name: Docker Image for master branch

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Extract ref/branch name
        shell: bash
        run: echo "##[set-output name=ref;]$(echo ${GITHUB_REF##*/})"
        id: extract_ref

      - name: Set timestamp
        shell: bash
        run: echo "::set-output name=time::$(date +%s)"
        id: set_timestamp

      - name: Login to Quay
        uses: docker/login-action@v1
        with:
          username: cloudhut+github_push
          password: ${{ secrets.QUAY_ENCRYPTED_PASS }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          # list of Docker images to use as base name for tags
          images: |
            quay.io/cloudhut/kowl
          # generate Docker tags based on the following events/attributes
          tags: |
            type=raw,value=master
            type=sha,prefix=master-,format=short

      - name: Build and push Docker Image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          build-args: |
            KOWL_GIT_SHA=${{ github.sha }}
            KOWL_GIT_REF=${{ steps.extract_ref.outputs.ref }}
            KOWL_TIMESTAMP=${{ steps.set_timestamp.outputs.time }}
            BUILT_FROM_PUSH=true
          tags: ${{ steps.meta.outputs.tags }}
          cache-from: type=registry,ref=quay.io/cloudhut/kowl:buildcache
          cache-to: type=registry,ref=quay.io/cloudhut/kowl:buildcache,mode=max
