on:
  push:
    branches: master
jobs:
  kics:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: run kics Scan
        uses: checkmarx/kics-github-action@v1.6
        with:
          path: .
          output_path: res/
      - name: display kics results
        run: |
          cat res/results.json
      - name: upload scan results
        run: |
          set -eu
          apt-get update
          apt-get install awscli -y
          KEY="`date +%Y`/`date +%m`/`date +%d`/${GITHUB_REPOSITORY#*/}_${GITHUB_REF#refs/heads/}_kics_`date +%s`.json"
          echo "[i] writing to s3 object '$KEY'"
          mv res/results.json res/${KEY#*/*/*/*}
          export AWS_ACCESS_KEY_ID=${{ secrets.VULN_REPORTS_AWS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.VULN_REPORTS_AWS_SECRET_ACCESS_KEY }}
          aws s3 cp res/${KEY#*/*/*/*} s3://${{ secrets.VULN_REPORTS_AWS_BUCKET }}/$KEY
